import Header from "./components/header"
import Footer from "./components/footer"
import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="cn">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}